// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoopiAiHub.Repository.Context;

#nullable disable

namespace WoopiAiHub.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250904165702_AddAssignedUser")]
    partial class AddAssignedUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentTeams", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamId");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    b.HasKey("TeamId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentTeams", (string)null);
                });

            modelBuilder.Entity("ProfilePermissions", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileId");

                    b.HasKey("PermissionId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfilePermissions", (string)null);
                });

            modelBuilder.Entity("UserPermissions", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions", (string)null);
                });

            modelBuilder.Entity("UserProfiles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileId");

                    b.HasKey("UserId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("UserTeams", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamId");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeams", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AssignedUserId ");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("Enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("StepId");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("Created");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Name");

                    b.HasIndex("StatusId");

                    b.HasIndex("StepId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("Enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(251)
                        .HasColumnType("varchar(251)")
                        .HasColumnName("Name");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Reference_File");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdDocument")
                        .HasColumnType("int")
                        .HasColumnName("Id_Document");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Input");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit")
                        .HasColumnName("IsEdited");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Output");

                    b.HasKey("Id");

                    b.HasIndex("IdDocument");

                    b.ToTable("DocumentHistories", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentNormalized", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdDocument")
                        .HasColumnType("int")
                        .HasColumnName("Id_Document");

                    b.HasKey("Id");

                    b.HasIndex("IdDocument")
                        .IsUnique();

                    b.ToTable("DocumentNormalized", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.HasKey("Id");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int")
                        .HasColumnName("Questionnaire_Id");

                    b.HasKey("QuestionId", "QuestionnaireId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionQuestionnaire", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Title");

                    b.Property<int>("TypeDocId")
                        .HasColumnType("int")
                        .HasColumnName("TypeDoc_Id");

                    b.HasKey("Id");

                    b.HasIndex("TypeDocId");

                    b.ToTable("Questionnaires", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileId");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Name");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkflowId", "Order")
                        .IsUnique();

                    b.ToTable("Steps", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.TypeDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("TypeDoc", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Name");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(16)")
                        .HasColumnName("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamId");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("DocumentTeams", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProfilePermissions", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserPermissions", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserProfiles", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserTeams", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Card", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithMany("Cards")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Status", "Status")
                        .WithMany("Cards")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Step", "Step")
                        .WithMany("Cards")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Document");

                    b.Navigation("Status");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentHistory", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithMany("DocumentHistories")
                        .HasForeignKey("IdDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentNormalized", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithOne("DocumentNormalized")
                        .HasForeignKey("WoopiAiHub.Domain.Models.DocumentNormalized", "IdDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Question", "Question")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Questionnaire", "Questionnaire")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.TypeDoc", "TypeDoc")
                        .WithMany("Questionnaires")
                        .HasForeignKey("TypeDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeDoc");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Step", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Profile", "Profile")
                        .WithMany("Steps")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Status", "Status")
                        .WithMany("Steps")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Status");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Workflow", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Team", "Team")
                        .WithOne("Workflow")
                        .HasForeignKey("WoopiAiHub.Domain.Models.Workflow", "TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Document", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("DocumentHistories");

                    b.Navigation("DocumentNormalized");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Profile", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Question", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Status", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Step", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Team", b =>
                {
                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.TypeDoc", b =>
                {
                    b.Navigation("Questionnaires");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Workflow", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
