// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoopiAiHub.Repository.Context;

#nullable disable

namespace WoopiAiHub.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107193126_cascade-deletion-for_profiles-teams")]
    partial class cascadedeletionfor_profilesteams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProfilePermissions", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileId");

                    b.HasKey("PermissionId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfilePermissions", (string)null);
                });

            modelBuilder.Entity("TeamProfiles", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamId");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileId");

                    b.HasKey("TeamId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("TeamProfiles", (string)null);
                });

            modelBuilder.Entity("UserPermissions", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions", (string)null);
                });

            modelBuilder.Entity("UserTeams", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamId");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeams", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AssignedUserId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("Enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("StepId");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("Created");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Name");

                    b.HasIndex("StatusId");

                    b.HasIndex("StepId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("Enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(251)
                        .HasColumnType("varchar(251)")
                        .HasColumnName("Name");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Reference_File");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdDocument")
                        .HasColumnType("int")
                        .HasColumnName("Id_Document");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Input");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit")
                        .HasColumnName("IsEdited");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Output");

                    b.HasKey("Id");

                    b.HasIndex("IdDocument");

                    b.ToTable("DocumentHistories", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentNormalized", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdDocument")
                        .HasColumnType("int")
                        .HasColumnName("Id_Document");

                    b.HasKey("Id");

                    b.HasIndex("IdDocument")
                        .IsUnique();

                    b.ToTable("DocumentNormalized", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(95)
                        .HasColumnType("varchar(95)")
                        .HasColumnName("Description");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueIdentifier")
                        .HasColumnName("IdUser");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("Prompts", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.HasKey("Id");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int")
                        .HasColumnName("Questionnaire_Id");

                    b.HasKey("QuestionId", "QuestionnaireId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionQuestionnaire", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Title");

                    b.Property<int>("TypeDocId")
                        .HasColumnType("int")
                        .HasColumnName("TypeDoc_Id");

                    b.HasKey("Id");

                    b.HasIndex("TypeDocId");

                    b.ToTable("Questionnaires", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileId");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Name");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkflowId", "Order")
                        .IsUnique();

                    b.ToTable("Steps", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepProfilePermission", b =>
                {
                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("StepId", "ProfileId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ProfileId");

                    b.ToTable("StepProfilePermissions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int?>("DependsOnStepToolId")
                        .HasColumnType("int")
                        .HasColumnName("DependsOnStepToolId");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("StepOrder");

                    b.Property<decimal>("PositionX")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("PositionX");

                    b.Property<decimal>("PositionY")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("PositionY");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("StepId");

                    b.Property<int>("ToolId")
                        .HasColumnType("int")
                        .HasColumnName("ToolId");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnStepToolId")
                        .IsUnique()
                        .HasFilter("[DependsOnStepToolId] IS NOT NULL");

                    b.HasIndex("StepId");

                    b.HasIndex("ToolId");

                    b.ToTable("StepTools", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CardId");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime")
                        .HasColumnName("Completed");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime")
                        .HasColumnName("Started");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("StepToolId")
                        .HasColumnType("int")
                        .HasColumnName("StepToolId");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("StepToolId");

                    b.ToTable("StepToolExecutions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CardId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("StepToolId")
                        .HasColumnType("int")
                        .HasColumnName("StepToolId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("StepToolId");

                    b.ToTable("StepToolOutputs", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<bool>("RequiredFile")
                        .HasColumnType("bit")
                        .HasColumnName("RequiredFile");

                    b.Property<int>("StepToolId")
                        .HasColumnType("int")
                        .HasColumnName("StepToolId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.Property<Guid?>("WebhookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WebhookId");

                    b.HasKey("Id");

                    b.HasIndex("StepToolId");

                    b.ToTable("StepToolParameters", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectorApiKey")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ConnectorApiKey");

                    b.Property<string>("ConnectorUrl")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ConnectorUrl");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("InputDataId")
                        .HasColumnType("int")
                        .HasColumnName("InputDataId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsEditableInput")
                        .HasColumnType("bit")
                        .HasColumnName("IsEditableInput");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("OutputDataId")
                        .HasColumnType("int")
                        .HasColumnName("OutputDataId");

                    b.Property<int>("ToolTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ToolTypeId");

                    b.HasKey("Id");

                    b.HasIndex("InputDataId");

                    b.HasIndex("OutputDataId");

                    b.HasIndex("ToolTypeId");

                    b.ToTable("Tools", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ToolData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ToolDatas", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ToolType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ToolTypes", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.TypeDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("TypeDoc", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Name");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(16)")
                        .HasColumnName("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("WorkflowDocuments", b =>
                {
                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    b.HasKey("WorkflowId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("WorkflowDocuments", (string)null);
                });

            modelBuilder.Entity("WorkflowTeams", b =>
                {
                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamId");

                    b.HasKey("WorkflowId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("WorkflowTeams", (string)null);
                });

            modelBuilder.Entity("ProfilePermissions", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamProfiles", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserPermissions", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserTeams", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Card", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithMany("Cards")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Status", "Status")
                        .WithMany("Cards")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Step", "Step")
                        .WithMany("Cards")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Document");

                    b.Navigation("Status");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentHistory", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithMany("DocumentHistories")
                        .HasForeignKey("IdDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentNormalized", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithOne("DocumentNormalized")
                        .HasForeignKey("WoopiAiHub.Domain.Models.DocumentNormalized", "IdDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Prompt", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.User", "User")
                        .WithMany("Prompts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Question", "Question")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Questionnaire", "Questionnaire")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.TypeDoc", "TypeDoc")
                        .WithMany("Questionnaires")
                        .HasForeignKey("TypeDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeDoc");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Step", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Profile", "Profile")
                        .WithMany("Steps")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Status", "Status")
                        .WithMany("Steps")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Status");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepProfilePermission", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Permission", "Permission")
                        .WithMany("StepProfilePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Profile", "Profile")
                        .WithMany("StepProfilePermissions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Step", "Step")
                        .WithMany("StepProfilePermissions")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Profile");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepTool", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "DependsOnStepTool")
                        .WithOne()
                        .HasForeignKey("WoopiAiHub.Domain.Models.StepTool", "DependsOnStepToolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WoopiAiHub.Domain.Models.Step", "Step")
                        .WithMany("StepTools")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Tool", "Tool")
                        .WithMany("StepTools")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependsOnStepTool");

                    b.Navigation("Step");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolExecution", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Card", "Card")
                        .WithMany("Executions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "StepTool")
                        .WithMany("Executions")
                        .HasForeignKey("StepToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("StepTool");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolOutput", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Card", "Card")
                        .WithMany("Outputs")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "StepTool")
                        .WithMany("Outputs")
                        .HasForeignKey("StepToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("StepTool");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolParameter", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "StepTool")
                        .WithMany("Parameters")
                        .HasForeignKey("StepToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepTool");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Tool", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.ToolData", "InputData")
                        .WithMany("InputTools")
                        .HasForeignKey("InputDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.ToolData", "OutputData")
                        .WithMany("OutputTools")
                        .HasForeignKey("OutputDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.ToolType", "ToolType")
                        .WithMany("Tools")
                        .HasForeignKey("ToolTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InputData");

                    b.Navigation("OutputData");

                    b.Navigation("ToolType");
                });

            modelBuilder.Entity("WorkflowDocuments", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowTeams", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Card", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Document", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("DocumentHistories");

                    b.Navigation("DocumentNormalized");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Permission", b =>
                {
                    b.Navigation("StepProfilePermissions");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Profile", b =>
                {
                    b.Navigation("StepProfilePermissions");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Question", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Status", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Step", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("StepProfilePermissions");

                    b.Navigation("StepTools");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepTool", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Outputs");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Tool", b =>
                {
                    b.Navigation("StepTools");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ToolData", b =>
                {
                    b.Navigation("InputTools");

                    b.Navigation("OutputTools");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ToolType", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.TypeDoc", b =>
                {
                    b.Navigation("Questionnaires");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.User", b =>
                {
                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Workflow", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
