// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoopiAiHub.Repository.Context;

#nullable disable

namespace WoopiAiHub.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625142753_AddApiAndN8NConnectorTools")]
    partial class AddApiAndN8NConnectorTools
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProfilePermissions", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileId");

                    b.HasKey("PermissionId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfilePermissions", (string)null);
                });

            modelBuilder.Entity("TeamProfiles", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamId");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileId");

                    b.HasKey("TeamId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("TeamProfiles", (string)null);
                });

            modelBuilder.Entity("UserPermissions", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions", (string)null);
                });

            modelBuilder.Entity("UserTeams", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamId");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeams", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ApiTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyTemplate")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("BodyTemplate");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Created")
                        .HasDefaultValueSql("(GETDATE())");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("EnableAccessFromMcp")
                        .HasColumnType("bit")
                        .HasColumnName("EnableAccessFromMcp");

                    b.Property<string>("HeaderTemplate")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("HeaderTemplate");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("QueryTemplate")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("QueryTemplate");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.ToTable("ApiTemplates", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Audit.AuditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int")
                        .HasColumnName("ActionType");

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CardId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("CardId");

                    b.HasIndex("Created");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("AuditCards", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Action");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TableName");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("TableName");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AssignedUserId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int?>("DocumentBatchId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentBatchId");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    b.Property<bool>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("StepId");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("Created");

                    b.HasIndex("DocumentBatchId")
                        .HasDatabaseName("IX_Cards_DocumentBatchId")
                        .HasFilter("[DocumentBatchId] IS NOT NULL");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Name");

                    b.HasIndex("StatusId");

                    b.HasIndex("StepId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<bool>("Enable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Enable");

                    b.Property<string>("ExtractionMode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Extraction_Mode");

                    b.Property<bool>("HasBatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("HasBatch");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(251)
                        .HasColumnType("varchar(251)")
                        .HasColumnName("Name");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Reference_File");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentAnalysisRejection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CardId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("Justification");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("StepId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("Created");

                    b.HasIndex("StepId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentAnalysisRejections", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentAnonymization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DocumentUrl");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentAnonymizations", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.HasKey("Id");

                    b.ToTable("DocumentBatchs", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdDocument")
                        .HasColumnType("int")
                        .HasColumnName("Id_Document");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Input");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit")
                        .HasColumnName("IsEdited");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Output");

                    b.Property<int?>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IdDocument");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentHistories", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentNormalized", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdDocument")
                        .HasColumnType("int")
                        .HasColumnName("Id_Document");

                    b.HasKey("Id");

                    b.HasIndex("IdDocument")
                        .IsUnique();

                    b.ToTable("DocumentNormalized", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ModelEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ModelEmbeddings");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Active");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("EnableAccessToMcp")
                        .HasColumnType("bit")
                        .HasColumnName("EnableAccessToMcp");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueIdentifier")
                        .HasColumnName("IdUser");

                    b.Property<bool>("IsEdited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsEdited");

                    b.Property<bool>("IsImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsImported");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Text");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("Prompts", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.PromptApiTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApiTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("PromptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApiTemplateId");

                    b.HasIndex("PromptId");

                    b.ToTable("PromptApiTemplates");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.HasKey("Id");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int")
                        .HasColumnName("Questionnaire_Id");

                    b.HasKey("QuestionId", "QuestionnaireId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionQuestionnaire", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Title");

                    b.Property<int>("TypeDocId")
                        .HasColumnType("int")
                        .HasColumnName("TypeDoc_Id");

                    b.HasKey("Id");

                    b.HasIndex("TypeDocId");

                    b.ToTable("Questionnaires", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(7)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Label");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int")
                        .HasColumnName("ProfileId");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("Name");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StatusId");

                    b.HasIndex("WorkflowId", "Order")
                        .IsUnique();

                    b.ToTable("Steps", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepProfilePermission", b =>
                {
                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("StepId", "ProfileId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ProfileId");

                    b.ToTable("StepProfilePermissions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepTool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int?>("DependsOnStepToolId")
                        .HasColumnType("int")
                        .HasColumnName("DependsOnStepToolId");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("StepOrder");

                    b.Property<decimal>("PositionX")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("PositionX");

                    b.Property<decimal>("PositionY")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("PositionY");

                    b.Property<int>("StepId")
                        .HasColumnType("int")
                        .HasColumnName("StepId");

                    b.Property<int>("ToolId")
                        .HasColumnType("int")
                        .HasColumnName("ToolId");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnStepToolId")
                        .IsUnique()
                        .HasFilter("[DependsOnStepToolId] IS NOT NULL");

                    b.HasIndex("StepId");

                    b.HasIndex("ToolId");

                    b.ToTable("StepTools", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("DependsOnStepToolId")
                        .HasColumnType("int")
                        .HasColumnName("DependsOnStepToolId");

                    b.Property<int>("StepToolId")
                        .HasColumnType("int")
                        .HasColumnName("StepToolId");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnStepToolId");

                    b.HasIndex("StepToolId", "DependsOnStepToolId")
                        .IsUnique();

                    b.ToTable("StepToolDependencies", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CardId");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("datetime")
                        .HasColumnName("Completed");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime")
                        .HasColumnName("Started");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("StepToolId")
                        .HasColumnType("int")
                        .HasColumnName("StepToolId");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("StepToolId", "CardId")
                        .HasDatabaseName("IX_StepToolExecution_StepToolId_CardId");

                    b.ToTable("StepToolExecutions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CardId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("StepToolId")
                        .HasColumnType("int")
                        .HasColumnName("StepToolId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("StepToolId");

                    b.ToTable("StepToolOutputs", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<bool>("RequiredFile")
                        .HasColumnType("bit")
                        .HasColumnName("RequiredFile");

                    b.Property<int>("StepToolId")
                        .HasColumnType("int")
                        .HasColumnName("StepToolId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.Property<Guid?>("WebhookId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WebhookId");

                    b.HasKey("Id");

                    b.HasIndex("StepToolId");

                    b.ToTable("StepToolParameters", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.SubscriptionPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit")
                        .HasColumnName("IsProcessed");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime")
                        .HasColumnName("PeriodStart");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPeriods", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.TenantLlmModelSetting", b =>
                {
                    b.Property<string>("Scope")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Scope");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ModelName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedByEmail")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UpdatedByEmail");

                    b.HasKey("Scope");

                    b.ToTable("TenantLlmModelSettings", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectorApiKey")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ConnectorApiKey");

                    b.Property<string>("ConnectorUrl")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ConnectorUrl");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("InputDataId")
                        .HasColumnType("int")
                        .HasColumnName("InputDataId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsEditableInput")
                        .HasColumnType("bit")
                        .HasColumnName("IsEditableInput");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<int>("OutputDataId")
                        .HasColumnType("int")
                        .HasColumnName("OutputDataId");

                    b.Property<int>("ToolTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ToolTypeId");

                    b.HasKey("Id");

                    b.HasIndex("InputDataId");

                    b.HasIndex("OutputDataId");

                    b.HasIndex("ToolTypeId");

                    b.ToTable("Tools", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ToolData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ToolDatas", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ToolType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ToolTypes", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.TypeDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("TypeDoc", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int?>("ModelEmbeddingId")
                        .HasColumnType("int")
                        .HasColumnName("ModelEmbeddingId");

                    b.Property<int>("Origin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Origin");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit")
                        .HasColumnName("Processed");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int")
                        .HasColumnName("UsageCount");

                    b.Property<int>("UsageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("UsageTypeId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int?>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("Created")
                        .HasDatabaseName("IX_UsageDaily_Created");

                    b.HasIndex("ModelEmbeddingId");

                    b.HasIndex("UsageTypeId");

                    b.HasIndex("Processed", "Created")
                        .HasDatabaseName("IX_UsageDaily_Processed_Created");

                    b.HasIndex("UserId", "Processed")
                        .HasDatabaseName("IX_UsageDaily_UserId_Processed");

                    b.HasIndex("WorkflowId", "Processed")
                        .HasDatabaseName("IX_UsageDaily_WorkflowId_Processed");

                    b.ToTable("UsageDailies");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int?>("ModelEmbeddingId")
                        .HasColumnType("int")
                        .HasColumnName("ModelEmbeddingId");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit")
                        .HasColumnName("Processed");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int")
                        .HasColumnName("UsageCount");

                    b.Property<int>("UsageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("UsageTypeId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ModelEmbeddingId");

                    b.HasIndex("UsageTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UsageLogs");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int?>("ModelEmbeddingId")
                        .HasColumnType("int")
                        .HasColumnName("ModelEmbeddingId");

                    b.Property<int>("Total")
                        .HasColumnType("int")
                        .HasColumnName("Total");

                    b.Property<int>("UsageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("UsageTypeId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<int?>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("ModelEmbeddingId");

                    b.HasIndex("UsageTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("UsageMonths");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("UsageTypes");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int?>("ModelEmbeddingId")
                        .HasColumnType("int")
                        .HasColumnName("ModelEmbeddingId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<int?>("UsageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("UsageTypeId");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,9)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ModelEmbeddingId");

                    b.HasIndex("UsageTypeId");

                    b.ToTable("UsageUnits");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(254)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime")
                        .HasColumnName("LastLoginAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Name");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(64)")
                        .HasColumnName("PasswordHash");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(16)")
                        .HasColumnName("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("Enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("WorkflowDocuments", b =>
                {
                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("DocumentId");

                    b.HasKey("WorkflowId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("WorkflowDocuments", (string)null);
                });

            modelBuilder.Entity("WorkflowTeams", b =>
                {
                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamId");

                    b.HasKey("WorkflowId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("WorkflowTeams", (string)null);
                });

            modelBuilder.Entity("ProfilePermissions", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamProfiles", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserPermissions", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserTeams", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Audit.AuditCard", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Document");

                    b.Navigation("User");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.AuditLog", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Card", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("WoopiAiHub.Domain.Models.DocumentBatch", "DocumentBatch")
                        .WithMany("Cards")
                        .HasForeignKey("DocumentBatchId");

                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithMany("Cards")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Status", "Status")
                        .WithMany("Cards")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Step", "Step")
                        .WithMany("Cards")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Document");

                    b.Navigation("DocumentBatch");

                    b.Navigation("Status");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentAnalysisRejection", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Step", "Step")
                        .WithMany()
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Step");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentAnonymization", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithMany("DocumentAnonymizations")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentHistory", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithMany("DocumentHistories")
                        .HasForeignKey("IdDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", "User")
                        .WithMany("DocumentHistories")
                        .HasForeignKey("UserId");

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentNormalized", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithOne("DocumentNormalized")
                        .HasForeignKey("WoopiAiHub.Domain.Models.DocumentNormalized", "IdDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Prompt", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.User", "User")
                        .WithMany("Prompts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.PromptApiTemplate", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.ApiTemplate", "ApiTemplate")
                        .WithMany("PromptApiTemplates")
                        .HasForeignKey("ApiTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Prompt", "Prompt")
                        .WithMany("PromptApiTemplates")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiTemplate");

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Question", "Question")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Questionnaire", "Questionnaire")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.TypeDoc", "TypeDoc")
                        .WithMany("Questionnaires")
                        .HasForeignKey("TypeDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeDoc");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Step", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Profile", "Profile")
                        .WithMany("Steps")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Status", "Status")
                        .WithMany("Steps")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Status");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepProfilePermission", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Permission", "Permission")
                        .WithMany("StepProfilePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Profile", "Profile")
                        .WithMany("StepProfilePermissions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Step", "Step")
                        .WithMany("StepProfilePermissions")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Profile");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepTool", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "DependsOnStepTool")
                        .WithOne()
                        .HasForeignKey("WoopiAiHub.Domain.Models.StepTool", "DependsOnStepToolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WoopiAiHub.Domain.Models.Step", "Step")
                        .WithMany("StepTools")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Tool", "Tool")
                        .WithMany("StepTools")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependsOnStepTool");

                    b.Navigation("Step");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolDependency", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "DependsOnStepTool")
                        .WithMany()
                        .HasForeignKey("DependsOnStepToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "StepTool")
                        .WithMany("Dependencies")
                        .HasForeignKey("StepToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnStepTool");

                    b.Navigation("StepTool");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolExecution", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Card", "Card")
                        .WithMany("Executions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "StepTool")
                        .WithMany("Executions")
                        .HasForeignKey("StepToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("StepTool");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolOutput", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Card", "Card")
                        .WithMany("Outputs")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "StepTool")
                        .WithMany("Outputs")
                        .HasForeignKey("StepToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("StepTool");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepToolParameter", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.StepTool", "StepTool")
                        .WithMany("Parameters")
                        .HasForeignKey("StepToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepTool");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Tool", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.ToolData", "InputData")
                        .WithMany("InputTools")
                        .HasForeignKey("InputDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.ToolData", "OutputData")
                        .WithMany("OutputTools")
                        .HasForeignKey("OutputDataId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.ToolType", "ToolType")
                        .WithMany("Tools")
                        .HasForeignKey("ToolTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InputData");

                    b.Navigation("OutputData");

                    b.Navigation("ToolType");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageDaily", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.ModelEmbedding", "ModelEmbedding")
                        .WithMany("UsageDaily")
                        .HasForeignKey("ModelEmbeddingId");

                    b.HasOne("WoopiAiHub.Domain.Models.UsageType", "UsageType")
                        .WithMany("UsageDaily")
                        .HasForeignKey("UsageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", "User")
                        .WithMany("UsageDailies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", "Workflow")
                        .WithMany("UsageDailies")
                        .HasForeignKey("WorkflowId");

                    b.Navigation("ModelEmbedding");

                    b.Navigation("UsageType");

                    b.Navigation("User");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageLog", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.ModelEmbedding", "ModelEmbedding")
                        .WithMany("UsageLog")
                        .HasForeignKey("ModelEmbeddingId");

                    b.HasOne("WoopiAiHub.Domain.Models.UsageType", "UsageType")
                        .WithMany("UsageLog")
                        .HasForeignKey("UsageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", "User")
                        .WithMany("UsageLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelEmbedding");

                    b.Navigation("UsageType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageMonth", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.ModelEmbedding", "ModelEmbedding")
                        .WithMany("UsageMonth")
                        .HasForeignKey("ModelEmbeddingId");

                    b.HasOne("WoopiAiHub.Domain.Models.UsageType", "UsageType")
                        .WithMany("UsageMonth")
                        .HasForeignKey("UsageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.User", "User")
                        .WithMany("UsageMonths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", "Workflow")
                        .WithMany("UsageMonths")
                        .HasForeignKey("WorkflowId");

                    b.Navigation("ModelEmbedding");

                    b.Navigation("UsageType");

                    b.Navigation("User");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageUnit", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.ModelEmbedding", "ModelEmbedding")
                        .WithMany("UsageUnits")
                        .HasForeignKey("ModelEmbeddingId");

                    b.HasOne("WoopiAiHub.Domain.Models.UsageType", "UsageType")
                        .WithMany("Units")
                        .HasForeignKey("UsageTypeId");

                    b.Navigation("ModelEmbedding");

                    b.Navigation("UsageType");
                });

            modelBuilder.Entity("WorkflowDocuments", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkflowTeams", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Workflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ApiTemplate", b =>
                {
                    b.Navigation("PromptApiTemplates");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Card", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Document", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("DocumentAnonymizations");

                    b.Navigation("DocumentHistories");

                    b.Navigation("DocumentNormalized");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentBatch", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ModelEmbedding", b =>
                {
                    b.Navigation("UsageDaily");

                    b.Navigation("UsageLog");

                    b.Navigation("UsageMonth");

                    b.Navigation("UsageUnits");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Permission", b =>
                {
                    b.Navigation("StepProfilePermissions");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Profile", b =>
                {
                    b.Navigation("StepProfilePermissions");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Prompt", b =>
                {
                    b.Navigation("PromptApiTemplates");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Question", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Status", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Step", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("StepProfilePermissions");

                    b.Navigation("StepTools");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.StepTool", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Executions");

                    b.Navigation("Outputs");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Tool", b =>
                {
                    b.Navigation("StepTools");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ToolData", b =>
                {
                    b.Navigation("InputTools");

                    b.Navigation("OutputTools");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.ToolType", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.TypeDoc", b =>
                {
                    b.Navigation("Questionnaires");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.UsageType", b =>
                {
                    b.Navigation("Units");

                    b.Navigation("UsageDaily");

                    b.Navigation("UsageLog");

                    b.Navigation("UsageMonth");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("DocumentHistories");

                    b.Navigation("Prompts");

                    b.Navigation("UsageDailies");

                    b.Navigation("UsageLogs");

                    b.Navigation("UsageMonths");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Workflow", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("UsageDailies");

                    b.Navigation("UsageMonths");
                });
#pragma warning restore 612, 618
        }
    }
}
