using Microsoft.EntityFrameworkCore;
using WoopiAiHub.Domain.DTOs.Response;
using WoopiAiHub.Domain.Enum;
using WoopiAiHub.Domain.Interfaces.Repository;
using WoopiAiHub.Domain.Models;
using WoopiAiHub.Repository.Context;
using WoopiAiHub.Repository.Util.Records;

namespace WoopiAiHub.Repository
{
    public class StepRepository : IStepRepository
    {
        private readonly ApplicationDbContext _context;
        public StepRepository(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Creates a new step in the database.
        /// </summary>
        /// <param name="step"></param>
        /// <returns></returns>
        public async Task<bool> Create(Step step)
        {
            _context.Steps.Add(step);
            return await _context.SaveChangesAsync() > 0;
        }

        public async Task CreateRange(ICollection<Step> steps)
        {
            await _context.Steps.AddRangeAsync(steps);
        }

        /// <summary>
        /// Updates an existing step in the database.
        /// </summary>
        /// <param name="step"></param>
        /// <returns></returns>
        public async Task<bool> Update(Step step)
        {
            _context.Steps.Update(step);
            return await _context.SaveChangesAsync() > 0;
        }

        /// <summary>
        /// Retrieves a step by its ID without tracking, including related profile, status, cards, and workflow.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<Step?> FindById(int id)
        {
            return await _context.Steps
                .Include(s => s.Profile)
                .Include(s => s.Status)
                .Include(s => s.Cards)
                .Include(s => s.Workflow)
                .AsNoTracking()
                .FirstOrDefaultAsync(s => s.Id == id);
        }

        /// <summary>
        /// Asynchronously retrieves a step by its unique identifier, including its associated tools.
        /// </summary>
        /// <remarks>The returned step includes its related tools loaded from the database. This method
        /// performs a database query and may return null if no step with the specified identifier exists.</remarks>
        /// <param name="id">The unique identifier of the step to retrieve.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains the step with its associated
        /// tools if found; otherwise, null.</returns>
        public async Task<Step?> FindByIdWithTools(int id)
        {
            return await _context.Steps
                .AsNoTracking()
                .Include(s => s.StepTools)
                .FirstOrDefaultAsync(s => s.Id == id);
        }

        /// <summary>
        /// Retrieves all steps associated with a specific workflow ID.
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public ICollection<Step> FindByIds(IEnumerable<int> ids)
        {
            return _context.Steps.AsNoTracking().Where(t => ids.Contains(t.Id))
                .ToList();
        }

        /// <summary>
        /// Retrieves all steps with cards associated with ids list
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public ICollection<Step> FindByIdsWithCards(IEnumerable<int> ids)
        {
            return _context.Steps.Where
                (t => ids.Contains(t.Id))
                .Include(t => t.Cards)
                .ToList();
        }

        /// <summary>
        /// Delete steps by their IDs.
        /// </summary>
        /// <param name="ids"></param>
        /// <returns></returns>
        public bool DeleteByIds(IEnumerable<int> ids)
        {
            if (!ids?.Any() ?? true)
                return false;

            var deletedCount = _context.Steps
                .Where(a => ids!.Contains(a.Id))
                .ExecuteDelete();

            return deletedCount > 0;
        }

        /// <summary>
        /// Finds a step by its order and workflow ID.
        /// </summary>
        /// <param name="order"></param>
        /// <param name="workflowId"></param>
        /// <returns></returns>
        public Task<Step?> FindByOrderAndWorkflowId(int order,
                                                    int workflowId)
        {
            return _context.Steps
                .Include(s => s.Profile)
                .AsNoTracking()
                .FirstOrDefaultAsync(s => s.Order == order &&
                                                     s.WorkflowId == workflowId);
        }

        /// <summary>
        /// Returns all steps of a workflow with their filtered cards and execution progress.
        /// Runs 3 focused queries to avoid the nested OUTER APPLY generated by a single large LINQ projection:
        /// 1) Steps — profile, status and tool flag.
        /// 2) Cards  — filtered by search text, assigned user and document type.
        /// 3) Executions — progress data for the cards found.
        /// Grouping by batch and percentage calculation are done in memory after the queries.
        /// </summary>
        public async Task<List<StepDto>> FindStepsByWorkflowId(
            int id,
            string input = "",
            bool allUsers = false,
            string login = "",
            string order = "",
            DocumentFilter documentFilter = DocumentFilter.All)
        {
            var steps = await LoadStepsAsync(id);
            if (steps.Count == 0) return steps;

            var stepIds = steps.Select(s => s.Id).ToList();
            var cards = await LoadCardsAsync(stepIds, input, allUsers, login, documentFilter);
            var executions = await LoadExecutionsAsync(cards.Select(c => c.Id).ToList());

            var cardsByStep = cards.GroupBy(c => c.StepId).ToDictionary(g => g.Key, g => g.ToList());
            var execsByStep = executions.GroupBy(e => e.StepId).ToDictionary(g => g.Key, g => g.ToList());

            foreach (var step in steps)
            {
                var stepCards = cardsByStep.GetValueOrDefault(step.Id, []);
                var stepExecs = execsByStep.GetValueOrDefault(step.Id, []);
                step.Cards = BuildCardDtos(stepCards, stepExecs);
            }

            steps.ForEach(step => step.Cards = ApplyCardOrdering(step.Cards, order));
            return steps;
        }

        /// <summary>
        /// Asynchronously retrieves all steps associated with the specified workflow, ordered by step identifier.
        /// </summary>
        /// <param name="workflowId">The unique identifier of the workflow whose steps are to be loaded.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains a list of <see cref="StepDto"/>
        /// objects for the specified workflow. If the workflow has no steps, the list will be empty.</returns>
        private async Task<List<StepDto>> LoadStepsAsync(int workflowId)
        {
            return await _context.Steps
                .AsNoTracking()
                .Where(s => s.WorkflowId == workflowId)
                .OrderBy(s => s.Id)
                .Select(s => new StepDto
                {
                    Id = s.Id,
                    Name = s.Name,
                    Order = s.Order,
                    WorkflowId = s.WorkflowId,
                    Profile = new ProfileDto { Id = s.Profile!.Id, Name = s.Profile.Name },
                    Status = new StatusDto { Id = s.Status!.Id, Name = s.Status.Name, Color = s.Status.Color },
                    HasStepTools = s.StepTools.Any(),
                })
                .ToListAsync();
        }

        /// <summary>
        /// Asynchronously retrieves a list of card projections that match the specified step IDs, input filter, user
        /// scope, and document filter criteria.
        /// </summary>
        /// <param name="stepIds">The list of step IDs to filter cards by. Only cards with a <c>StepId</c> contained in this list are
        /// included.</param>
        /// <param name="input">An optional search string used to filter cards by name, document name, document description, or document
        /// creator's email. If <paramref name="input"/> is <see langword="null"/> or whitespace, this filter is not
        /// applied.</param>
        /// <param name="allUsers"><see langword="true"/> to include cards assigned to any user; <see langword="false"/> to include only cards
        /// assigned to the user specified by <paramref name="login"/>.</param>
        /// <param name="login">The email address of the user whose assigned cards should be included when <paramref name="allUsers"/> is
        /// <see langword="false"/>. Ignored if <paramref name="allUsers"/> is <see langword="true"/>.</param>
        /// <param name="documentFilter">A value indicating which document types to include: all documents, only singles, or only batches.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains a list of <see
        /// cref="CardProjection"/> objects matching the specified filters. The list will be empty if no cards meet the
        /// criteria.</returns>
        private async Task<List<CardProjection>> LoadCardsAsync(
            List<int> stepIds,
            string input,
            bool allUsers,
            string login,
            DocumentFilter documentFilter)
        {
            return await _context.Cards
                .AsNoTracking()
                .Where(c => stepIds.Contains(c.StepId))
                .Where(c =>
                    string.IsNullOrWhiteSpace(input)
                    || c.Name.Contains(input)
                    || c.Document!.Name.Contains(input)
                    || c.Document.Description.Contains(input)
                    || c.Document.EmailCreator.Contains(input))
                .Where(c => allUsers || (c.AssignedUser != null && c.AssignedUser.Email == login))
                .Where(c =>
                    documentFilter == DocumentFilter.All
                    || (documentFilter == DocumentFilter.Singles && c.DocumentBatchId == null)
                    || (documentFilter == DocumentFilter.Batches && c.DocumentBatchId != null))
                .Select(c => new CardProjection(
                    c.Id,
                    c.Name,
                    c.Created,
                    c.DocumentBatchId,
                    c.StepId,
                    c.Document!.Id,
                    c.Document.Description,
                    c.Document.EmailCreator,
                    c.Document.Status,
                    (Guid?)c.AssignedUser!.Id,
                    (string?)c.AssignedUser.Name,
                    (string?)c.AssignedUser.Email,
                    (DateTime?)c.AssignedUser.Created,
                    c.Status!.Id,
                    c.Status.Name,
                    c.Status.Color))
                .ToListAsync();
        }

        /// <summary>
        /// Asynchronously retrieves execution projections for the specified card IDs.
        /// </summary>
        /// <param name="cardIds">The list of card IDs for which to load execution projections. Must not be empty.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains a list of <see
        /// cref="ExecutionProjection"/> objects corresponding to the specified card IDs. If <paramref name="cardIds"/>
        /// is empty, the returned list will also be empty.</returns>
        private async Task<List<ExecutionProjection>> LoadExecutionsAsync(List<int> cardIds)
        {
            if (cardIds.Count == 0) return [];

            return await _context.StepToolExecutions
                .AsNoTracking()
                .Where(e => cardIds.Contains(e.CardId))
                .Select(e => new ExecutionProjection(
                    e.CardId,
                    e.StepToolId,
                    e.Status,
                    e.StepTool!.StepId,
                    e.StepTool.Tool!.Name))
                .ToListAsync();
        }

        /// <summary>
        /// Groups cards by batch (DocumentBatchId ?? -Id), picks the first card of each group
        /// as the representative and calculates Percentage and ToolName from executions.
        /// </summary>
        private static List<CardDto> BuildCardDtos(
            List<CardProjection> cards,
            List<ExecutionProjection> executions)
        {
            return cards
                .GroupBy(c => c.DocumentBatchId ?? -c.Id)
                .Select(group =>
                {
                    var representative = group.MinBy(c => c.Id)!;
                    var groupCardIds = group.Select(c => c.Id).ToHashSet();
                    var groupExecs = executions.Where(e => groupCardIds.Contains(e.CardId)).ToList();

                    return new CardDto
                    {
                        Id = representative.Id,
                        Name = representative.Name,
                        Created = representative.Created,
                        Description = representative.DocumentDescription,
                        Owner = representative.DocumentOwner,
                        DocumentId = representative.DocumentId,
                        StatusDocument = representative.DocumentStatus,
                        Percentage = CalculatePercentage(groupCardIds, groupExecs),
                        ToolName = FindRunningToolName(groupExecs),
                        AssignedUser = BuildAssignedUser(representative),
                        Status = new StatusDto
                        {
                            Id = representative.StatusId,
                            Name = representative.StatusName,
                            Color = representative.StatusColor,
                        },
                        IsBatchParent = representative.DocumentBatchId != null,
                    };
                })
                .ToList();
        }

        /// <summary>
        /// Percentage = (StepTools where ALL cards in the group have a Ready execution / total StepTools with any execution) * 100.
        /// Returns 100 when no executions exist yet (card not started).
        /// </summary>
        private static int CalculatePercentage(HashSet<int> groupCardIds, List<ExecutionProjection> groupExecs)
        {
            var stepToolsWithExecs = groupExecs.Select(e => e.StepToolId).ToHashSet();
            if (stepToolsWithExecs.Count == 0) return 100;

            var completed = stepToolsWithExecs.Count(stId =>
            {
                var toolExecs = groupExecs.Where(e => e.StepToolId == stId).ToList();
                return groupCardIds.All(cardId =>
                    toolExecs.Any(e => e.CardId == cardId && e.Status == StatusExecution.Ready));
            });

            return completed * 100 / stepToolsWithExecs.Count;
        }

        /// <summary>
        /// Returns the name of the tool associated with the first execution in the list that is currently running.
        /// </summary>
        /// <param name="groupExecs">The list of <see cref="ExecutionProjection"/> instances to search for a running execution. Cannot be null.</param>
        /// <returns>The <see cref="ExecutionProjection.ToolName"/> of the first execution with a status of <see
        /// cref="StatusExecution.Running"/>;  otherwise, an empty string if no such execution is found.</returns>
        private static string FindRunningToolName(List<ExecutionProjection> groupExecs)
        {
            return groupExecs.FirstOrDefault(e => e.Status == StatusExecution.Running)?.ToolName ?? "";
        }

        /// <summary>
        /// Creates a <see cref="UserDto"/> representing the user assigned to the specified card.
        /// </summary>
        /// <param name="card">The <see cref="CardProjection"/> containing assignment information. Must not be <c>null</c>.</param>
        /// <returns>A <see cref="UserDto"/> populated with the assigned user's details if the card has an assigned user;
        /// otherwise, <c>null</c>.</returns>
        private static UserDto? BuildAssignedUser(CardProjection card)
        {
            if (card.AssignedUserId is null) return null;

            return new UserDto
            {
                Id = card.AssignedUserId.Value,
                Name = card.AssignedUserName!,
                Email = card.AssignedUserEmail!,
                Created = card.AssignedUserCreated!.Value,
            };
        }

        /// <summary>
        /// Retrieves a list of steps in the specified workflow that precede the current step of the given card.
        /// </summary>
        /// <remarks>Use this method to determine the steps that a card has already passed through or
        /// could have passed through in a workflow. The returned steps are ordered according to their position in the
        /// workflow.</remarks>
        /// <param name="workflowId">The unique identifier of the workflow to search within.</param>
        /// <param name="order">order.</param>
        /// <returns>A list of <see cref="StepDto"/> objects representing the steps that occur before the current step of the
        /// specified card in the workflow. Returns an empty list if no previous steps are found.</returns>
        public async Task<List<StepDto>> FindPreviousStepsByWorkflowIdAndOrder(int workflowId, int order)
        {
            return await _context.Steps
                .Where(s => s.WorkflowId == workflowId && s.Order < order)
                .Select(s => new StepDto
                {
                    Id = s.Id,
                    Name = s.Name,
                    Order = s.Order,
                    WorkflowId = s.WorkflowId
                })
                .AsNoTracking()
                .ToListAsync();
        }

        /// <summary>
        /// finds the step associated with a specific card ID.
        /// </summary>
        /// <param name="cardId"></param>
        /// <returns></returns>
        public Task<Step?> FindStepByCardId(int cardId)
        {
            return _context.Cards
                .AsNoTracking()
                .Where(c => c.Id == cardId)
                .Select(c => c.Step)
                .FirstOrDefaultAsync();
        }

        /// <summary>
        /// Applies ordering to a collection of CardDto based on the specified orderBy string.
        /// </summary>
        /// <param name="cards"></param>
        /// <param name="orderBy"></param>
        /// <returns></returns>
        private static ICollection<CardDto> ApplyCardOrdering(ICollection<CardDto> cards, string? orderBy)
        {
            return orderBy?.ToLower() switch
            {
                "created desc" => cards.OrderByDescending(c => c.Created).ToList(),
                "created asc" => cards.OrderBy(c => c.Created).ToList(),
                "name desc" => cards.OrderByDescending(c => c.Name).ToList(),
                "name asc" => cards.OrderBy(c => c.Name).ToList(),
                _ => cards
            };
        }
    }
}
