// <auto-generated />
using System;
using WoopiAiHub.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WoopiAiHub.Repository.Migrations.applicationDB
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240116190840_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EmailCreator");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("Enable");

                    b.Property<string>("NrIDEA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nr_IDEA");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Reference_File");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Inquiries", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.InquiryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdInquiry")
                        .HasColumnType("int")
                        .HasColumnName("Id_Inquiry");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Input");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Output");

                    b.HasKey("Id");

                    b.HasIndex("IdInquiry");

                    b.ToTable("InquiryHistories", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.InquiryNormalized", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdInquiry")
                        .HasColumnType("int")
                        .HasColumnName("Id_Inquiry");

                    b.HasKey("Id");

                    b.HasIndex("IdInquiry")
                        .IsUnique();

                    b.ToTable("InquiryNormalized", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.InquiryHistory", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Inquiry", "Inquiry")
                        .WithMany("InquiryHistories")
                        .HasForeignKey("IdInquiry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquiry");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.InquiryNormalized", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Inquiry", "Inquiry")
                        .WithOne("InquiryNormalized")
                        .HasForeignKey("WoopiAiHub.Domain.Models.InquiryNormalized", "IdInquiry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquiry");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Inquiry", b =>
                {
                    b.Navigation("InquiryHistories");

                    b.Navigation("InquiryNormalized");
                });
#pragma warning restore 612, 618
        }
    }
}
