// <auto-generated />
using System;
using WoopiAiHub.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WoopiAiHub.Repository.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("Enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(251)
                        .HasColumnType("varchar(251)")
                        .HasColumnName("Name");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Reference_File");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdDocument")
                        .HasColumnType("int")
                        .HasColumnName("Id_Document");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Input");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit")
                        .HasColumnName("IsEdited");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Output");

                    b.HasKey("Id");

                    b.HasIndex("IdDocument");

                    b.ToTable("DocumentHistories", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentNormalized", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdDocument")
                        .HasColumnType("int")
                        .HasColumnName("Id_Document");

                    b.HasKey("Id");

                    b.HasIndex("IdDocument")
                        .IsUnique();

                    b.ToTable("DocumentNormalized", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.HasKey("Id");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int")
                        .HasColumnName("Questionnaire_Id");

                    b.HasKey("QuestionId", "QuestionnaireId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionQuestionnaire", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Title");

                    b.Property<int>("TypeDocId")
                        .HasColumnType("int")
                        .HasColumnName("TypeDoc_Id");

                    b.HasKey("Id");

                    b.HasIndex("TypeDocId");

                    b.ToTable("Questionnaires", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.TypeDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("TypeDoc", (string)null);
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentHistory", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithMany("DocumentHistories")
                        .HasForeignKey("IdDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.DocumentNormalized", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Document", "Document")
                        .WithOne("DocumentNormalized")
                        .HasForeignKey("WoopiAiHub.Domain.Models.DocumentNormalized", "IdDocument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.Question", "Question")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoopiAiHub.Domain.Models.Questionnaire", "Questionnaire")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.HasOne("WoopiAiHub.Domain.Models.TypeDoc", "TypeDoc")
                        .WithMany("Questionnaires")
                        .HasForeignKey("TypeDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeDoc");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Document", b =>
                {
                    b.Navigation("DocumentHistories");

                    b.Navigation("DocumentNormalized");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Question", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.Questionnaire", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("WoopiAiHub.Domain.Models.TypeDoc", b =>
                {
                    b.Navigation("Questionnaires");
                });
#pragma warning restore 612, 618
        }
    }
}
