// <auto-generated />
using System;
using DocAnalyzer.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocAnalyzer.Repository.Migrations.applicationDB
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240326123639_add-email-creator")]
    partial class addemailcreator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocAnalyzer.Domain.Models.Inquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EmailCreator");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("Enable");

                    b.Property<string>("NrIDEA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nr_IDEA");

                    b.Property<string>("ReferenceFile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Reference_File");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Inquiries", (string)null);
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.InquiryHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdInquiry")
                        .HasColumnType("int")
                        .HasColumnName("Id_Inquiry");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Input");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Output");

                    b.HasKey("Id");

                    b.HasIndex("IdInquiry");

                    b.ToTable("InquiryHistories", (string)null);
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.InquiryNormalized", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<int>("IdInquiry")
                        .HasColumnType("int")
                        .HasColumnName("Id_Inquiry");

                    b.HasKey("Id");

                    b.HasIndex("IdInquiry")
                        .IsUnique();

                    b.ToTable("InquiryNormalized", (string)null);
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EmailCreator");

                    b.HasKey("Id");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("Question_Id");

                    b.Property<int>("QuestionnaireId")
                        .HasColumnType("int")
                        .HasColumnName("Questionnaire_Id");

                    b.HasKey("QuestionId", "QuestionnaireId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("QuestionQuestionnaire", (string)null);
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.Questionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Title");

                    b.Property<int>("TypeDocId")
                        .HasColumnType("int")
                        .HasColumnName("TypeDoc_Id");

                    b.HasKey("Id");

                    b.HasIndex("TypeDocId");

                    b.ToTable("Questionnaires", (string)null);
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.TypeDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<string>("EmailCreator")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EmailCreator");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("TypeDoc", (string)null);
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.InquiryHistory", b =>
                {
                    b.HasOne("DocAnalyzer.Domain.Models.Inquiry", "Inquiry")
                        .WithMany("InquiryHistories")
                        .HasForeignKey("IdInquiry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquiry");
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.InquiryNormalized", b =>
                {
                    b.HasOne("DocAnalyzer.Domain.Models.Inquiry", "Inquiry")
                        .WithOne("InquiryNormalized")
                        .HasForeignKey("DocAnalyzer.Domain.Models.InquiryNormalized", "IdInquiry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquiry");
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.QuestionQuestionnaire", b =>
                {
                    b.HasOne("DocAnalyzer.Domain.Models.Question", "Question")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocAnalyzer.Domain.Models.Questionnaire", "Questionnaire")
                        .WithMany("QuestionQuestionnaire")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.Questionnaire", b =>
                {
                    b.HasOne("DocAnalyzer.Domain.Models.TypeDoc", "TypeDoc")
                        .WithMany("Questionnaires")
                        .HasForeignKey("TypeDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeDoc");
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.Inquiry", b =>
                {
                    b.Navigation("InquiryHistories");

                    b.Navigation("InquiryNormalized");
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.Question", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.Questionnaire", b =>
                {
                    b.Navigation("QuestionQuestionnaire");
                });

            modelBuilder.Entity("DocAnalyzer.Domain.Models.TypeDoc", b =>
                {
                    b.Navigation("Questionnaires");
                });
#pragma warning restore 612, 618
        }
    }
}
