name: 'Build image file-repository'

on:
  push:
    branches:
      - 'trocar_develop'
    paths:
      - 'external-api/**'

jobs:
  build-image:
    name: "Build image file-repository"
    runs-on: ["azure-identity"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image
        working-directory: ./external-api
        run: docker image build -t acrapplications.azurecr.io/woopi-ai/doc-file-repository:latest .

      - name: Azure login
        run: az login --identity
  
      - name: ACR login
        run: az acr login -n acrapplications
      
      - name: Push Image
        run: docker image push acrapplications.azurecr.io/woopi-ai/doc-file-repository:latest
