name: 'Build image functions'

on:
  push:
    branches:
      - 'develop'
      - 'release'
    # paths:
      # - 'back-end/WoopiAiHub.Functions/**'

jobs:
  build-image:
    name: "Build image functions"
    runs-on: ["azure-identity"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Declare variables
        id: vars
        run: |
          echo "imageRepository=woopi-ai" >> $GITHUB_OUTPUT
          echo "imageName=woopiai-hub-functions" >> $GITHUB_OUTPUT

          echo "imageVersion=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          
      - name: Build Image
        working-directory: ./back-end/WoopiAiHub.Functions
        run: docker image build -t acrapplications.azurecr.io/${{steps.vars.outputs.imageRepository}}/${{steps.vars.outputs.imageName}}:${{steps.vars.outputs.imageVersion}} .

      - name: Azure login
        run: az login --identity
  
      - name: ACR login
        run: az acr login -n acrapplications
      
      - name: Push Image
        run: docker image push acrapplications.azurecr.io/${{steps.vars.outputs.imageRepository}}/${{steps.vars.outputs.imageName}}:${{steps.vars.outputs.imageVersion}}

