name: 'Build and Test'

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ["azure"]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
          
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
            8.0.x

      - name: Nuget Restore
        run: |
          dotnet restore

      - name: Build
        run: |
          dotnet build back-end/DocAnalyzer.Api/DocAnalyzer.Api.csproj
          dotnet build external-api/FileRepository.Api/FileRepository.Api.csproj
          dotnet build tests/DocAnalyzer.UnitTests/DocAnalyzer.UnitTests.csproj

      - name: Unit Tests
        run: |
          dotnet test --no-restore --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: phoenix-actions/test-reporting@v15
        id: test-report
        if: success() || failure()
        with:
          name: DOTNET Tests
          path: tests/DocAnalyzer.UnitTests/TestResults/test-results.trx
          reporter: dotnet-trx
          output-to: 'step-summary'
